import type {Metadata} from 'next';
import Providers from '@/config/providers';

export const metadata: Metadata = {
  title: 'CRUD',
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <Providers>
      {children}
    </Providers>
    </body>
    </html>
  );
}
